// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_HomeScn
void ui_HomeScn_screen_init(void);
void ui_event_HomeScn(lv_event_t * e);
extern lv_obj_t * ui_HomeScn;
extern lv_obj_t * ui_starImg;
extern lv_obj_t * ui_timeLbl;
extern lv_obj_t * ui_ampmLbl;
extern lv_obj_t * ui_dateLbl;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_cryptoRateLbl;
extern lv_obj_t * ui_arrowImg;
extern lv_obj_t * ui_cryptoPercentageLbl;
extern lv_obj_t * ui_cryptoNameLbl;
extern lv_obj_t * ui_stepCountArc;
extern lv_obj_t * ui_stepCountLbl;
extern lv_obj_t * ui_stepsLbl;
extern lv_obj_t * ui_tempuratureArc;
extern lv_obj_t * ui_tempLbl;
extern lv_obj_t * ui_batteryArc;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES

// SCREEN: ui_MenuScn
void ui_MenuScn_screen_init(void);
void ui_event_MenuScn(lv_event_t * e);
extern lv_obj_t * ui_MenuScn;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Dropdown1;
// CUSTOM VARIABLES

// SCREEN: ui_WifiScn
void ui_WifiScn_screen_init(void);
extern lv_obj_t * ui_WifiScn;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_star_png);    // assets/star.png
LV_IMG_DECLARE(ui_img_up_triangle_png);    // assets/up_triangle.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png

// FONTS
LV_FONT_DECLARE(ui_font_inter16sb);
LV_FONT_DECLARE(ui_font_inter20b);
LV_FONT_DECLARE(ui_font_inter20sb);
LV_FONT_DECLARE(ui_font_inter32sb);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
