// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"

void brightnessChangecallback(lv_event_t * e)
{
	// get the value of the slider
	lv_obj_t * slider = lv_event_get_target(e);
	uint8_t value = lv_slider_get_value(slider);

	// convert that value to 0-255 range
	uint8_t brightness =	(uint8_t)(value * 255 / 100);
	
	if(brightness < 30) brightness = 30;

	// set the brightness
	analogWrite(2, brightness);
}

void addNewWiFicallback(lv_event_t * e)
{
	// set the flag
	setOndemardWifi = true;
}

void backToHomeCB(lv_event_t * e)
{
	// Your code here
	_ui_screen_change(&ui_HomeScn, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_HomeScn_screen_init);
}

void cancelWiFiCB(lv_event_t * e)
{
	// Your code here
	cancelOnDemandWifi = true;
	
}
