// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomeScn_screen_init(void)
{
    ui_HomeScn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomeScn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_starImg = lv_image_create(ui_HomeScn);
    lv_image_set_src(ui_starImg, &ui_img_star_png);
    lv_obj_set_width(ui_starImg, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_starImg, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_starImg, -11);
    lv_obj_set_y(ui_starImg, 36);
    lv_obj_set_align(ui_starImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_starImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_starImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeLbl = lv_label_create(ui_HomeScn);
    lv_obj_set_width(ui_timeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLbl, -20);
    lv_obj_set_y(ui_timeLbl, -58);
    lv_obj_set_align(ui_timeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLbl, "00:00");
    lv_obj_set_style_text_color(ui_timeLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_timeLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_timeLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLbl, &ui_font_inter32sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ampmLbl = lv_label_create(ui_HomeScn);
    lv_obj_set_width(ui_ampmLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ampmLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ampmLbl, 48);
    lv_obj_set_y(ui_ampmLbl, -55);
    lv_obj_set_align(ui_ampmLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ampmLbl, "XX");
    lv_obj_set_style_text_color(ui_ampmLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampmLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ampmLbl, &ui_font_inter20sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLbl = lv_label_create(ui_HomeScn);
    lv_obj_set_width(ui_dateLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLbl, 0);
    lv_obj_set_y(ui_dateLbl, -90);
    lv_obj_set_align(ui_dateLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLbl, "00-00  XXX");
    lv_obj_set_style_text_color(ui_dateLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateLbl, &ui_font_inter16sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_HomeScn);
    lv_obj_set_width(ui_Panel5, 230);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, -5);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cryptoRateLbl = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cryptoRateLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cryptoRateLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cryptoRateLbl, -28);
    lv_obj_set_y(ui_cryptoRateLbl, 0);
    lv_obj_set_align(ui_cryptoRateLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cryptoRateLbl, "--:--");
    lv_obj_set_style_text_color(ui_cryptoRateLbl, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cryptoRateLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cryptoRateLbl, &ui_font_inter32sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arrowImg = lv_image_create(ui_Panel5);
    lv_image_set_src(ui_arrowImg, &ui_img_up_triangle_png);
    lv_obj_set_width(ui_arrowImg, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_arrowImg, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_arrowImg, 90);
    lv_obj_set_y(ui_arrowImg, -10);
    lv_image_set_scale(ui_arrowImg, 180);
    lv_obj_set_align(ui_arrowImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrowImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_arrowImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cryptoPercentageLbl = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cryptoPercentageLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cryptoPercentageLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cryptoPercentageLbl, 90);
    lv_obj_set_y(ui_cryptoPercentageLbl, 6);
    lv_obj_set_align(ui_cryptoPercentageLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cryptoPercentageLbl, "0.0%");
    lv_obj_set_style_text_color(ui_cryptoPercentageLbl, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cryptoPercentageLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cryptoPercentageLbl, &ui_font_inter16sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cryptoNameLbl = lv_label_create(ui_HomeScn);
    lv_obj_set_width(ui_cryptoNameLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cryptoNameLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cryptoNameLbl, 19);
    lv_obj_set_y(ui_cryptoNameLbl, 36);
    lv_obj_set_align(ui_cryptoNameLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cryptoNameLbl, "XDC");
    lv_obj_set_style_text_color(ui_cryptoNameLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cryptoNameLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cryptoNameLbl, &ui_font_inter20b, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_stepCountArc = lv_arc_create(ui_HomeScn);
    // lv_obj_set_width(ui_stepCountArc, 60);
    // lv_obj_set_height(ui_stepCountArc, 60);
    // lv_obj_set_x(ui_stepCountArc, -63);
    // lv_obj_set_y(ui_stepCountArc, 55);
    // lv_obj_set_align(ui_stepCountArc, LV_ALIGN_CENTER);
    // lv_obj_remove_flag(ui_stepCountArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
    //                    LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
    //                    LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    // lv_arc_set_value(ui_stepCountArc, 100);
    // lv_arc_set_bg_angles(ui_stepCountArc, 65, 64);
    // lv_obj_set_style_arc_width(ui_stepCountArc, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_arc_color(ui_stepCountArc, lv_color_hex(0x00FF55), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_opa(ui_stepCountArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_width(ui_stepCountArc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // lv_obj_set_style_bg_color(ui_stepCountArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_stepCountArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // ui_stepCountLbl = lv_label_create(ui_stepCountArc);
    // lv_obj_set_width(ui_stepCountLbl, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_stepCountLbl, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_stepCountLbl, 0);
    // lv_obj_set_y(ui_stepCountLbl, -3);
    // lv_obj_set_align(ui_stepCountLbl, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_stepCountLbl, "0");
    // lv_obj_set_style_text_color(ui_stepCountLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_stepCountLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_stepCountLbl, &ui_font_inter20b, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_stepsLbl = lv_label_create(ui_stepCountArc);
    // lv_obj_set_width(ui_stepsLbl, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_stepsLbl, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_stepsLbl, 0);
    // lv_obj_set_y(ui_stepsLbl, 12);
    // lv_obj_set_align(ui_stepsLbl, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_stepsLbl, "steps");
    // lv_obj_set_style_text_color(ui_stepsLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_stepsLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_align(ui_stepsLbl, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_decor(ui_stepsLbl, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_stepsLbl, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempuratureArc = lv_arc_create(ui_HomeScn);
    lv_obj_set_width(ui_tempuratureArc, 50);
    lv_obj_set_height(ui_tempuratureArc, 50);
    lv_obj_set_x(ui_tempuratureArc, -8);
    lv_obj_set_y(ui_tempuratureArc, 88);
    lv_obj_set_align(ui_tempuratureArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempuratureArc,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_tempuratureArc, 100);
    lv_arc_set_bg_angles(ui_tempuratureArc, 65, 64);
    lv_obj_set_style_arc_width(ui_tempuratureArc, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_tempuratureArc, lv_color_hex(0x00FF55), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempuratureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_tempuratureArc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempuratureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempuratureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempLbl = lv_label_create(ui_tempuratureArc);
    lv_obj_set_width(ui_tempLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLbl, "21°C");
    lv_obj_set_style_text_color(ui_tempLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLbl, &ui_font_inter20b, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryArc = lv_arc_create(ui_HomeScn);
    lv_obj_set_width(ui_batteryArc, 40);
    lv_obj_set_height(ui_batteryArc, 40);
    lv_obj_set_x(ui_batteryArc, 44);
    lv_obj_set_y(ui_batteryArc, 85);
    lv_obj_set_align(ui_batteryArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_batteryArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_batteryArc, 100);
    lv_arc_set_bg_angles(ui_batteryArc, 65, 64);
    lv_obj_set_style_arc_width(ui_batteryArc, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_batteryArc, lv_color_hex(0x00FF55), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batteryArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batteryArc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batteryArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_batteryArc);
    lv_image_set_src(ui_Image2, &ui_img_battery_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 8);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image2, 900);
    lv_image_set_scale(ui_Image2, 200);

    ui_Label6 = lv_label_create(ui_batteryArc);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -5);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "100");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_inter12sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_HomeScn);
    lv_obj_set_width(ui_Panel2, 24);
    lv_obj_set_height(ui_Panel2, 24);
    lv_obj_set_x(ui_Panel2, 81);
    lv_obj_set_y(ui_Panel2, 63);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Panel2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_HomeScn);
    lv_obj_set_width(ui_Panel1, 15);
    lv_obj_set_height(ui_Panel1, 15);
    lv_obj_set_x(ui_Panel1, 98);
    lv_obj_set_y(ui_Panel1, 39);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Panel1, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_HomeScn);
    lv_obj_set_width(ui_Button1, 60);
    lv_obj_set_height(ui_Button1, 60);
    lv_obj_set_x(ui_Button1, -64);
    lv_obj_set_y(ui_Button1, 58);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x00FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnLbl = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_btnLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_btnLbl, -1);
    lv_obj_set_y(ui_btnLbl, 1);
    lv_obj_set_align(ui_btnLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnLbl, "BTC");
    lv_obj_set_style_text_color(ui_btnLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnLbl, &ui_font_inter20sb, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeScn, ui_event_HomeScn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
