// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_WifiScn_screen_init(void)
{
    ui_WifiScn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiScn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiScn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiScn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
